### ISSUE TITLE
Publish on update

### ISSUE THREAD

**Issue by robmarkcole** [pimoroni/micropython-envirobit#2]
Hi
this isn't an issue but a request for advice. I only want to publish readings when there are significant updates, as using `sleep` severely limits functionality. Would you recommend something like https://github.com/peterhinch/micropython-async ?

**Comment by Gadgetoid** [comment]
Honestly when it comes to MicroPython on the micro:bit, all bets are off. Any attempt I've made to make these libraries any more than absolute barebones has been met with resource/stack errors.

I am reasonably confident that trying to run any sort of async library on the micro:bit would be a fruitless and painful endeavour, but I understand where you're coming from.

Here's a somewhat more lightweight approach that might help, though: https://github.com/kjagiello/microbit-sandbox/blob/master/main.py

I wholeheartedly (and this is coming from someone who writes and maintains Python libraries predominately) recommend trying out MakeCode/PXT on the micro:bit. Don't let the shiny block-based interface fool you- it's TypeScript under the hood and compiles down to native instructions so that you can get a lot more bang for your buck.

PXT has some form of co-operative multitasking and will allow you to interleave multiple processes together, more or less, by having it swap tasks when `sleep` is called. It's a steep learning curve if you haven't encountered JavaScript before, however.

**Comment by robmarkcole** [comment]
Thanks for the advice, I've no experience with JavaScript but I will take a look.
