### ISSUE TITLE
Altitude values clearly incorrect

### ISSUE THREAD

**Issue by robmarkcole** [pimoroni/micropython-envirobit#3]
HI 
the altitude values drift all over the shop, so I question their value. The following data was collected over the weekend, when the envirobit was stationary on a desk..

![image](https://user-images.githubusercontent.com/11855322/43368943-15e25b54-935d-11e8-964d-f5ee2401cb11.png)

**Comment by Gadgetoid** [comment]
Altitude is approximated as an offset from your local QNH - atmospheric pressure adjusted to mean sea level. It's by no means a direct measurement of altitude, and is thus only as good as the data you put in.

On the micro:bit this is problematic since it's difficult to continually supply an updated QNH value for your area.

The internal calculation for approximating altitutde is:

```
self._altitude = 44330.0 * (1.0 - pow(self._pressure / self._qnh, (1.0/5.255)))
```

And the QNH value required is a standard unit you can look up on Google for your region and then supply to the library with `set_qnh`. This will change on a regular basis with local air pressure.
