### ISSUE TITLE
How to use the drivers without MU?

### ISSUE THREAD

**Issue by jogyth** [pimoroni/micropython-envirobit#4]
Not an issue, but I'm kinda new to python and I'm wondering how I could use this drivers without running MU. I'm currently building from Sublime Text 3.  Any hints on how I can include the files using (any) other editor? Sorry for the newbie question ...

**Comment by Gadgetoid** [comment]
You'd need some combination of uflash and microfs to get the library onto the micro:bit with your code-

* https://github.com/ntoll/uflash
* https://github.com/ntoll/microfs

There might  be a Sublime Text addon that helps, but since MU relies on using `microfs` to sideload the Python scripts, and I'm not sure if `uflash` allows you to pack additional scripts into your code, you're probably better just using MU.

A quick google turns up - https://packagecontrol.io/packages/microbit%20Build%20System - which is 3 years out of date!
