### ISSUE TITLE
humidity values seem to be wrong

### ISSUE THREAD

**Issue by 0maunz0** [pimoroni/micropython-envirobit#6]
I am running  little DIY weather stations with 2 microbits each. One is running with the enviro:bit and sending the data to the second one which writes it to an SD-card through an OpenLog. 
The reported humidity values are definitely not correct though, as the appear to be directly proportional to the temperature. (See the attached images for the logged values over a period of roughly 6 days)
<img src="https://user-images.githubusercontent.com/24377217/92390441-24adc380-f11b-11ea-9ba4-21ed1aba39e5.png" width="500">
<img src="https://user-images.githubusercontent.com/24377217/92390442-24adc380-f11b-11ea-963d-ccfc131a6fc1.png" width="500">
As an comparison I have data from a weather station run by an university in my city, which covers roughly the same timeframe:
<img src="https://user-images.githubusercontent.com/24377217/92390436-237c9680-f11b-11ea-9b57-f8eb55c17187.png" width="500">
<img src="https://user-images.githubusercontent.com/24377217/92390439-24152d00-f11b-11ea-974a-e9f755913982.png" width="500">

The code was written in the Mu editor, I have attached the code for the microbit that is running the envirobit:
[main.txt](https://github.com/pimoroni/micropython-envirobit/files/5183236/main.txt)

If a similar setup is run with the makecode blocks language, reasonable values were obtained (same devices, same enclosure, slightly different weather conditions). For energy efficiency reasons, I tried to do it via micropython which allows me to send the microbit to sleep. Removing the sleep command does not change the reported values.

**Comment by Gadgetoid** [comment]
There's definitely something broken in the library, but I can't quite track down exactly what. I've hooked up an enviro:bit to a Raspberry Pi to run our CPython BME280 library and get some significantly different and much more responsive humidity readings.

I even swapped out our library for a *very* cut down version of Adafruit's and still get the same output on the micro:bit.

I've tried ensuring the humidity oversampling register is set on init, but it doesn't appear to be that either... I'm clearly missing something.


Edit2: snipped code paste because it's redundant. Commit incoming.

**Comment by Gadgetoid** [comment]
Okay, after *much* sleuthing and more or less an entire day weeping over code I finally realised- due to some dim recollection of having encountered this problem before- that the humidity had not been properly enabled, or- rather- the oversampling was not being set- and my initial attempts to set it did not occur in the correct order.

Try the code as of https://github.com/pimoroni/micropython-envirobit/commit/e3d07362f5a7c65cfcd348b157ae81a345fd539d and it should- hopefully- work!

**Comment by 0maunz0** [comment]
Seems to be working fine now - getting pretty similar values as with the makecode blocks language. My understanding of the matter is sadly not at a level where I can figure such things out myself. So thank you a lot for taking the time to find the issue and fixing the code!

**Comment by Gadgetoid** [comment]
Hooray! Thank you for letting me know.

And no worries- as out on a limb as this Python code is, it's still my job to maintain it 😆  sorry it wasted your time and filled your graph history with nonsense values.
